UPDATE shows Set title = 'Adventure Time' WHERE title = 'adventure time';
UPDATE shows Set title = 'Arrow' WHERE title = 'arrow';
UPDATE shows Set title = 'Avatar: The Last Airbender' WHERE title = 'avatar the last airbender';
UPDATE shows Set title = 'Brooklyn Nine-Nine' WHERE title = 'brooklyn 99';
UPDATE shows Set title = 'Community' WHERE title = 'community';
UPDATE shows Set title = 'Family Guy' WHERE title = 'family guy';
UPDATE shows Set title = 'Friends' WHERE title = 'friends';
UPDATE shows Set title = 'Game of Thrones' WHERE title = 'Game Of Thrones';
UPDATE shows Set title = 'Gilmore Girls' WHERE ID = '73';
UPDATE shows Set title = 'Grey’s Anatomy' WHERE ID = '153';
UPDATE shows Set title = 'How I Met Your Mother' WHERE title = 'how i met your mother';
UPDATE shows Set title = 'It’s Always Sunny in Philadelphia' WHERE title = 'Its Always Sunny in Philidelphia';
UPDATE shows Set title = 'Parks and Recreation' = 'Parks and Rec';
UPDATE shows Set title = 'Sherlock' WHERE ID = '83';
UPDATE shows Set title = 'Squid Game' WHERE title = 'squid game';
UPDATE shows Set title = 'The Bachelorette' WHERE title = 'the bachelorette';
UPDATE shows Set title = 'The Crown' WHERE title = 'The CROWN';
UPDATE shows Set title = 'The Office' WHERE title = 'Thevoffice';
UPDATE shows Set title = "The Queen's Gambit" WHERE ID = '173';
UPDATE shows Set title = 'The Untamed' WHERE title = 'the Utamed';
